### ISSUE TITLE
Files interface is ignored during type generation

### ISSUE THREAD

**Issue by MrEraxd** [bryantgillespie/directus-sdk-typegen#5]
Files interface is not being added to generated types, here is a screenshot from directus:

![image](https://github.com/user-attachments/assets/8baab0bc-e7db-4873-9ee6-818076887200)

And here is generated type:

![image](https://github.com/user-attachments/assets/b613fb88-7a8f-4f7e-a024-626bc5a36081)

I think it should look like this instead:

![image](https://github.com/user-attachments/assets/7facc57d-31a3-4c23-a47d-87eefc672cc6)

**Comment by bryantgillespie** [comment]
Should be fixed now. Try v 0.1.9
https://github.com/bryantgillespie/directus-sdk-typegen/commit/b62223cee668d58e17dd775c53861ef576b5300f

**Comment by MrEraxd** [comment]
Works flawlessly. Thanks a lot!

**Comment by bryantgillespie** [comment]
> Works flawlessly. Thanks a lot!

Thanks for spotting it! Keep the feedback coming.
